secret:
  jwt:
    key: ENC(pJyY2N352qhAcC5/6lWtro6d+For9hI/cbua7SMbP121jsewpaMHYz4z22zwo+w4blILvGWLuSsVh7fb8bbx4Gi3YAwoCv3rXOuXQikAt4o=)
    signature: ENC(6FZdAAIi2htp3OwQzOqnmK5tbtNLVvGO)

  kakao:
    admin-key: ENC(sFSNf8T3aiThdhCu9yHQb0bBLpVTkk/50UJpxgYhxRvk6JZ/xdcIk85OB17YboiM)
    client-id: ENC(egCrmTnMY/kGZNYJwP7O+dHISas8fVWFmO4bF9M6zkDHi02moIaexhENauQDBduD)
    client-secret: ENC(Eo3sbkxTa8NAnpb3OOhhhKMeu+O9KBpsIQsDL57wiISyA6T+wqfaaeJglbyurx3h)
    logout-redirect-url: ENC(cQFggzXPK6NQs7Aj/K1V5zlkGvJcXLtvNPsWBx7KiQ2DFxeoMi2+w41q9go7gIoHQ1pDFM+l++g=)

  naver:
    service-id: ENC(KGYbqFQjZW4xYno34IweG24a6Zz+3XirLecUbQ3JyNGCXe0H4UhjP+RIW8JsDdQA)
    access-key: ENC(SPmlxNClw9rBA7g9XT89qwOnG1ZCemEYm4DV9ps/Xtg=)
    secret-key: ENC(MpTl8HcBlRs4YifDssjdG3c2A7w3DZqHr4JkDXVN79tjbQuJ5dhZGyzg64132Q4KT+KAmMxQsBk=)
